# Generated by Django 5.1.2 on 2025-02-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_userprofile_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(
                choices=[('regular_account', 'Regular Account'), ('premium_account', 'Premium Account'),
                         ('business_account', 'Business Account')], default='regular_account', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
