# Generated by Django 5.1.6 on 2025-03-10 12:38

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_ministry_skill_memberprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ministry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select a ministry"),
                    ("worship", "Worship Team"),
                    ("youth", "Youth Ministry"),
                    ("children", "Children's Ministry"),
                    ("outreach", "Outreach & Missions"),
                    ("prayer", "Prayer Team"),
                    ("admin", "Administration"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ContentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_sermons", models.BooleanField(default=True)),
                ("show_devotionals", models.BooleanField(default=True)),
                ("show_bible_studies", models.BooleanField(default=True)),
                ("show_community_posts", models.BooleanField(default=True)),
                ("agree_guidelines", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinistryPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worship_team", models.BooleanField(default=False)),
                ("children_ministry", models.BooleanField(default=False)),
                ("youth_ministry", models.BooleanField(default=False)),
                ("outreach_ministry", models.BooleanField(default=False)),
                ("prayer_team", models.BooleanField(default=False)),
                ("hospitality_team", models.BooleanField(default=False)),
                ("sunday_morning", models.BooleanField(default=False)),
                ("sunday_evening", models.BooleanField(default=False)),
                ("weekdays", models.BooleanField(default=False)),
                ("special_events", models.BooleanField(default=False)),
                (
                    "spiritual_gifts",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("teaching", "Teaching"),
                            ("worship", "Worship/Music"),
                            ("service", "Service"),
                            ("leadership", "Leadership"),
                            ("encouragement", "Encouragement"),
                            ("giving", "Giving"),
                            ("mercy", "Mercy"),
                            ("hospitality", "Hospitality"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministry_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivacySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_email", models.BooleanField(default=False)),
                ("show_phone", models.BooleanField(default=False)),
                ("show_address", models.BooleanField(default=False)),
                ("show_prayers", models.BooleanField(default=True)),
                ("show_events", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_bible_verses", models.BooleanField(default=True)),
                ("show_prayer_requests", models.BooleanField(default=True)),
                ("show_events", models.BooleanField(default=True)),
                (
                    "preferred_bible",
                    models.CharField(
                        choices=[
                            ("niv", "New International Version (NIV)"),
                            ("kjv", "King James Version (KJV)"),
                            ("nlt", "New Living Translation (NLT)"),
                            ("esv", "English Standard Version (ESV)"),
                            ("nkjv", "New King James Version (NKJV)"),
                        ],
                        default="niv",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
