# Generated by Django 5.1.6 on 2025-03-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_userprofile_ministry_contentsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_setting",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="setting",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
