# Generated by Django 5.1.6 on 2025-03-11 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_userprofile_city_userprofile_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiritualGift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "church user",
                "verbose_name_plural": "church users",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="notification_setting",
        ),
        migrations.RemoveField(
            model_name="user",
            name="setting",
        ),
        migrations.AddField(
            model_name="user",
            name="baptism_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, default="United States", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="email_opt_in",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="family_id",
            field=models.CharField(
                blank=True, help_text="ID to link family members", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer not to say"),
                ],
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_attendance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("separated", "Separated"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="membership_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="membership_status",
            field=models.CharField(
                choices=[
                    ("visitor", "Visitor"),
                    ("regular", "Regular Attendee"),
                    ("member", "Member"),
                    ("leader", "Ministry Leader"),
                    ("staff", "Staff"),
                    ("pastor", "Pastor"),
                    ("elder", "Elder"),
                ],
                default="visitor",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ministry_interests",
            field=models.ManyToManyField(
                blank=True, related_name="interested_users", to="accounts.ministry"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="secondary_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="secondary email address"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_phone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="sms_opt_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="spouse_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="spiritual_gifts",
            field=models.ManyToManyField(
                blank=True, related_name="gifted_users", to="accounts.spiritualgift"
            ),
        ),
        migrations.CreateModel(
            name="VolunteerTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("sunday", "Sunday"),
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "unique_together": {("day", "time")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="volunteer_availability",
            field=models.ManyToManyField(
                blank=True,
                related_name="available_users",
                to="accounts.volunteertimeslot",
            ),
        ),
    ]
