# Generated by Django 5.1.2 on 2025-02-03 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0010_rename_comment_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at']},
        ),
    ]
