# Generated by Django 5.1.2 on 2025-02-03 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0011_alter_comments_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortvideo',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='shortvideo',
            old_name='upload_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='shortvideo',
            name='uploader',
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='created_shorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_shorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='thumbnail',
            field=models.ImageField(default='short_video.jpg', upload_to='short_video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='category',
            field=models.CharField(
                choices=[('worship', 'Worship'), ('testimony', 'Testimony'), ('sermon', 'Sermon Highlight'),
                         ('youth', 'Youth'), ('events', 'Events')], default='worship', max_length=50),
        ),
    ]
