# Generated by Django 5.1.2 on 2025-02-04 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0012_alter_shortvideo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortvideo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories',
                                    to='videos.category'),
        ),
    ]
