# Generated by Django 5.1.2 on 2025-02-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0015_remove_playlist_name_remove_playlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
