# Generated by Django 5.1.2 on 2025-02-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0016_playlist_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.IntegerField(default=0),
        ),
    ]
