# Generated by Django 5.1.2 on 2025-02-04 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0018_watchedvideo_delete_videohistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.queue')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.content')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('queue', 'position')},
            },
        ),
        migrations.AddField(
            model_name='queue',
            name='videos',
            field=models.ManyToManyField(through='videos.QueueItem', to='videos.content'),
        ),
    ]
