# Generated by Django 5.1.2 on 2025-02-05 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0020_alter_content_options_downloadedvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(related_name='in_playlists', through='videos.PlaylistVideo',
                                         to='videos.content'),
        ),
    ]
