# Generated by Django 5.1.2 on 2025-02-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='preacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='scripture_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('MUSIC', 'music'), ('SERMON', 'Sermon'), ('PREACHING', 'preaching'), ('BIBLE_STUDY', 'bible_study'), ('PRAISE_AND_WORSHIP', 'praise_and_worship'), ('ALL_TESTIMONIES', 'all_testimonies'), ('BIBLE_DISCUSSIONS', 'bible_discussions'), ('EVANGELISM', 'evangelism'), ('STREET_PRAISE_AND_WORSHIP_MUSIC_AND_PREACHING', 'street_worship_music'), ('GOSPEL_MADE_FOR_KIDS', 'gospel_made_for_kids'), ('GENERAL', 'General')], default='GENERAL', max_length=100),
        ),
    ]
