# Generated by Django 5.1.2 on 2025-02-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_content_preacher_content_scripture_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='preacher',
        ),
        migrations.RemoveField(
            model_name='content',
            name='scripture_reference',
        ),
    ]
