# Generated by Django 5.1.2 on 2025-02-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_remove_content_preacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('SERMON', 'Sermon'), ('GOSPEL', 'Gospel'), ('PRAISE_AND_WORSHIP', 'Praise and Worship'), ('TESTIMONY', 'Testimony'), ('BIBLE_STUDY', 'Bible Study'), ('GENERAL', 'General')], default='GENERAL', max_length=100),
        ),
    ]
