# Generated by Django 5.1.6 on 2025-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0026_alter_content_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="category",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
