# Generated by Django 5.1.6 on 2025-02-21 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0027_playlist_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptureReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book", models.CharField(max_length=50)),
                ("chapter", models.IntegerField()),
                ("verse_start", models.IntegerField()),
                ("verse_end", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("composer", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HY", "Hymn"),
                            ("CC", "Contemporary Christian"),
                            ("GO", "Gospel"),
                            ("WS", "Worship Song"),
                            ("CH", "Children's Song"),
                        ],
                        max_length=2,
                    ),
                ),
                ("key", models.CharField(max_length=10)),
                ("time_signature", models.CharField(max_length=10)),
                ("tempo", models.IntegerField()),
                ("ccli_number", models.CharField(blank=True, max_length=20)),
                ("verse_1", models.TextField()),
                ("chorus", models.TextField()),
                ("verse_2", models.TextField(blank=True)),
                ("bridge", models.TextField(blank=True)),
                (
                    "audio_sample",
                    models.FileField(blank=True, upload_to="song_samples/"),
                ),
                ("sheet_music", models.FileField(blank=True, upload_to="sheet_music/")),
                (
                    "chord_chart",
                    models.FileField(blank=True, upload_to="chord_charts/"),
                ),
                (
                    "backing_track",
                    models.FileField(blank=True, upload_to="backing_tracks/"),
                ),
                ("tutorial_video", models.URLField(blank=True)),
                ("has_translations", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scripture_references",
                    models.ManyToManyField(blank=True, to="videos.scripturereference"),
                ),
                ("themes", models.ManyToManyField(blank=True, to="videos.theme")),
            ],
            options={
                "verbose_name": "Song",
                "verbose_name_plural": "Songs",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videos.playlist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="videos.song"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("playlist", "song")},
            },
        ),
    ]
