# Generated by Django 5.1.6 on 2025-02-24 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0028_scripturereference_theme_song_playlistsong"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                ("description", models.TextField()),
                ("video_file", models.FileField(upload_to="videos/")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="video_thumbnails/"),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WO", "Worship"),
                            ("TE", "Teaching"),
                            ("SE", "Sermon"),
                            ("TY", "Testimony"),
                            ("MU", "Music"),
                            ("YO", "Youth"),
                            ("CH", "Children"),
                            ("MI", "Missions"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=500)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PU", "Public"),
                            ("PR", "Private"),
                            ("UN", "Unlisted"),
                        ],
                        default="PU",
                        max_length=2,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("captions", models.JSONField(blank=True, default=dict)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("has_profanity", models.BooleanField(default=False)),
                (
                    "processing_status",
                    models.CharField(default="pending", max_length=20),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videos.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["title"], name="videos_vide_title_8a2e81_idx"),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["category"], name="videos_vide_categor_c4366b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["user"], name="videos_vide_user_id_10d070_idx"),
        ),
    ]
