# Generated by Django 5.1.6 on 2025-02-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0029_video_comment_video_videos_vide_title_8a2e81_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scripturereference",
            name="book",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="scripturereference",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
