# Generated by Django 5.1.6 on 2025-03-10 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("tithe", "Tithe"),
                            ("missions", "Missions"),
                            ("building", "Building Fund"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("recurring", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recurring_tithe", models.BooleanField(default=False)),
                ("recurring_missions", models.BooleanField(default=False)),
                ("recurring_building_fund", models.BooleanField(default=False)),
                (
                    "preferred_payment_method",
                    models.CharField(
                        choices=[
                            ("creditCard", "Credit/Debit Card"),
                            ("bankTransfer", "Bank Transfer (ACH)"),
                            ("paypal", "PayPal"),
                        ],
                        default="creditCard",
                        max_length=20,
                    ),
                ),
                (
                    "donation_receipts",
                    models.CharField(
                        choices=[
                            ("immediately", "Send immediately"),
                            ("monthly", "Send monthly summary"),
                            ("quarterly", "Send quarterly summary"),
                            ("annually", "Send annual summary only"),
                        ],
                        default="immediately",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
