# Generated by Django 5.1.6 on 2025-03-11 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("creditCard", "Credit/Debit Card"),
                            ("bankAccount", "Bank Account"),
                        ],
                        default="creditCard",
                        max_length=20,
                    ),
                ),
                ("card_type", models.CharField(blank=True, max_length=50, null=True)),
                ("last_four", models.CharField(max_length=4)),
                ("expiry_date", models.CharField(blank=True, max_length=7, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
