# Generated by Django 5.1.6 on 2025-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0002_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="payment_last_four",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="recurring_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                ],
                default="monthly",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donation_type",
            field=models.CharField(
                choices=[
                    ("tithe", "Tithe"),
                    ("missions", "Missions Fund"),
                    ("building", "Building Fund"),
                    ("other", "Other"),
                ],
                default="tithe",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
