# Generated by Django 5.1.6 on 2025-02-21 10:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("biography", models.TextField()),
                ("image", models.ImageField(upload_to="artists/")),
                ("website", models.URLField(blank=True)),
                ("social_media", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("biography", models.TextField()),
                ("photo", models.ImageField(blank=True, upload_to="author_photos/")),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("SERMON", "Sermon"),
                            ("STUDY", "Bible Study"),
                            ("ARTICLE", "Article"),
                            ("VIDEO", "Video"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScriptureReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book", models.CharField(max_length=50)),
                ("chapter", models.IntegerField()),
                ("verse_start", models.IntegerField()),
                ("verse_end", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("cover_image", models.ImageField(upload_to="album_covers/")),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="resources.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BibleStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "study_type",
                    models.CharField(
                        choices=[
                            ("OT", "Old Testament"),
                            ("NT", "New Testament"),
                            ("TH", "Theology"),
                            ("DC", "Doctrine"),
                            ("AP", "Apologetics"),
                        ],
                        max_length=2,
                    ),
                ),
                ("scripture_reference", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "materials",
                    models.FileField(blank=True, upload_to="bible_study_materials/"),
                ),
                ("video_link", models.URLField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bible Studies",
            },
        ),
        migrations.CreateModel(
            name="BibleStudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="bible_study_materials/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OLD_TESTAMENT", "Old Testament"),
                            ("NEW_TESTAMENT", "New Testament"),
                            ("THEOLOGY", "Theology"),
                            ("DISCIPLESHIP", "Discipleship"),
                            ("COMMENTARY", "Commentary"),
                        ],
                        default="THEOLOGY",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_studies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible Study Material",
                "verbose_name_plural": "Bible Study Materials",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="ChristianBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("publication_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TH", "Theology"),
                            ("DV", "Devotional"),
                            ("BS", "Bible Study"),
                            ("CM", "Christian Living"),
                            ("AP", "Apologetics"),
                            ("BG", "Biography"),
                            ("CH", "Church History"),
                            ("FM", "Family"),
                            ("YT", "Youth"),
                            ("CH", "Children"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField()),
                ("cover_image", models.ImageField(upload_to="book_covers/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("pages", models.IntegerField()),
                ("publisher", models.CharField(max_length=200)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_bestseller", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.author",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyDevotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("scripture_reference", models.CharField(max_length=100)),
                ("scripture_text", models.TextField()),
                ("devotional_content", models.TextField()),
                ("prayer_focus", models.TextField()),
                ("publication_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Devotion",
                "verbose_name_plural": "Daily Devotions",
                "ordering": ["-publication_date"],
            },
        ),
        migrations.CreateModel(
            name="ReadingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("books", models.ManyToManyField(to="resources.christianbook")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TH", "Theology"),
                            ("BI", "Biblical Studies"),
                            ("DE", "Devotional"),
                            ("CH", "Church History"),
                            ("AP", "Apologetics"),
                            ("MI", "Ministry"),
                            ("DI", "Discipleship"),
                            ("PR", "Prayer"),
                            ("WO", "Worship"),
                            ("LE", "Leadership"),
                        ],
                        default="TH",
                        max_length=2,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="book_covers/"),
                ),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=13, verbose_name="ISBN"),
                ),
                ("pdf_file", models.FileField(blank=True, upload_to="book_files/")),
                (
                    "sample_chapter",
                    models.FileField(blank=True, upload_to="book_samples/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="resources_b_title_fe1f7e_idx"),
                    models.Index(
                        fields=["author"], name="resources_b_author_065bc4_idx"
                    ),
                    models.Index(
                        fields=["category"], name="resources_b_categor_9867d7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BookReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources.christianbook",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("book", "user")},
            },
        ),
    ]
