# Generated by Django 5.1.2 on 2025-02-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(
                    choices=[('SERMON', 'Sermon'), ('STUDY', 'Bible Study'), ('ARTICLE', 'Article'),
                             ('VIDEO', 'Video')], max_length=10)),
                ('content', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
            ],
        ),
    ]
