# Generated by Django 5.1.6 on 2025-02-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SermonNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("preacher", models.CharField(max_length=100)),
                ("date_preached", models.DateField()),
                ("bible_reference", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SUN", "Sunday Service"),
                            ("MID", "Midweek Service"),
                            ("SPE", "Special Service"),
                            ("YTH", "Youth Service"),
                            ("CON", "Conference"),
                            ("REV", "Revival"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "main_points",
                    models.TextField(help_text="Enter the main points of the sermon"),
                ),
                (
                    "key_scriptures",
                    models.TextField(help_text="Enter key scripture references"),
                ),
                ("summary", models.TextField()),
                (
                    "application_points",
                    models.TextField(
                        help_text="Practical application points from the sermon"
                    ),
                ),
                ("additional_notes", models.TextField(blank=True)),
                (
                    "audio_recording",
                    models.FileField(
                        blank=True, null=True, upload_to="sermon_recordings/"
                    ),
                ),
                (
                    "slides",
                    models.FileField(blank=True, null=True, upload_to="sermon_slides/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sermon Note",
                "verbose_name_plural": "Sermon Notes",
                "ordering": ["-date_preached"],
            },
        ),
    ]
