# Generated by Django 5.1.6 on 2025-02-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_sermonnotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("DOC", "Word Document"),
                            ("PPT", "PowerPoint"),
                            ("VID", "Video"),
                            ("AUD", "Audio"),
                            ("WEB", "Web Resource"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BIB", "Bible Study"),
                            ("THE", "Theology"),
                            ("DIS", "Discipleship"),
                            ("EVA", "Evangelism"),
                            ("LEA", "Leadership"),
                            ("YOU", "Youth Ministry"),
                            ("CHI", "Children Ministry"),
                            ("WOR", "Worship"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="teaching_resources/"
                    ),
                ),
                ("external_link", models.URLField(blank=True, null=True)),
                ("author", models.CharField(max_length=100)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "Teaching Resource",
                "verbose_name_plural": "Teaching Resources",
                "ordering": ["-upload_date"],
            },
        ),
    ]
