# Generated by Django 5.1.6 on 2025-02-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0003_teachingresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("host", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SER", "Sermons"),
                            ("BIB", "Bible Study"),
                            ("DEV", "Devotional"),
                            ("YOU", "Youth"),
                            ("WOR", "Worship"),
                            ("LEA", "Leadership"),
                            ("EVA", "Evangelism"),
                            ("TES", "Testimonies"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        help_text="Square image recommended (1400x1400px)",
                        upload_to="podcasts/covers/",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="podcasts/audio/")),
                (
                    "duration",
                    models.DurationField(help_text="Duration in HH:MM:SS format"),
                ),
                ("publish_date", models.DateTimeField()),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "keywords",
                    models.CharField(
                        help_text="Comma-separated keywords", max_length=500
                    ),
                ),
                ("explicit_content", models.BooleanField(default=False)),
                ("play_count", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                ("audio_type", models.CharField(default="audio/mpeg", max_length=50)),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("transcript", models.TextField(blank=True)),
                ("show_notes", models.TextField(blank=True)),
                ("share_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Podcast Episode",
                "verbose_name_plural": "Podcast Episodes",
                "ordering": ["-publish_date"],
            },
        ),
    ]
