# Generated by Django 5.1.6 on 2025-02-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("resources", "0004_podcast"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("planned", "Planned"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="missions/"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("team_size", models.IntegerField(default=0)),
                ("impact_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DownloadableResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="downloads/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="downloads/thumbnails/"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("DOC", "Word Document"),
                            ("PPT", "PowerPoint"),
                            ("XLS", "Excel Spreadsheet"),
                            ("ZIP", "ZIP Archive"),
                            ("IMG", "Image"),
                            ("VID", "Video"),
                            ("AUD", "Audio"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BIB", "Bible Study"),
                            ("SER", "Sermon Notes"),
                            ("WOR", "Worship Resources"),
                            ("CHI", "Children Ministry"),
                            ("YTH", "Youth Ministry"),
                            ("EVA", "Evangelism"),
                            ("DIS", "Discipleship"),
                            ("LEA", "Leadership"),
                            ("PRA", "Prayer"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("version", models.CharField(blank=True, max_length=20)),
                ("file_size", models.BigIntegerField(editable=False, null=True)),
                ("file_type", models.CharField(editable=False, max_length=50)),
                ("is_public", models.BooleanField(default=True)),
                ("requires_login", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                ("last_downloaded", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("allowed_groups", models.ManyToManyField(blank=True, to="auth.group")),
            ],
            options={
                "verbose_name": "Downloadable Resource",
                "verbose_name_plural": "Downloadable Resources",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("healthcare", "Healthcare"),
                            ("community", "Community Development"),
                            ("evangelism", "Evangelism"),
                            ("disaster", "Disaster Relief"),
                            ("youth", "Youth Empowerment"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(max_length=200)),
                ("project_lead", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("goals", models.TextField()),
                ("outcomes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="resources.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="project_updates/"
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="resources.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
