# Generated by Django 5.1.6 on 2025-02-24 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0005_mission_downloadableresource_project_projectupdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="mission",
        ),
        migrations.RemoveField(
            model_name="projectupdate",
            name="project",
        ),
        migrations.DeleteModel(
            name="Mission",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectUpdate",
        ),
    ]
