# Generated by Django 5.1.2 on 2025-02-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_biblereadingplan_coupleevent_coupleresource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblereading',
            name='plan',
        ),
        migrations.DeleteModel(
            name='BibleReadingPlan',
        ),
    ]
