# Generated by Django 5.1.2 on 2025-02-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_biblereadingplan_biblereading_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='reply_form',
            field=models.TextField(null=True),
        ),
    ]
