# Generated by Django 5.1.2 on 2025-02-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_forumtopic_reply_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrequest',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='occasion',
            field=models.CharField(choices=[('sunday_service', 'Sunday Service'), ('special_event', 'Special Event'), ('youth_service', 'Youth Service'), ('prayer_meeting', 'Prayer Meeting'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='song_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
