# Generated by Django 5.1.6 on 2025-02-18 10:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_songrequest_artist_alter_songrequest_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='biblereadingplan',
            name='completed_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biblereadingplan',
            name='couples',
            field=models.ManyToManyField(related_name='reading_plans', to='services.coupleprofile'),
        ),
        migrations.AddField(
            model_name='biblereadingplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biblereadingplan',
            name='plan_type',
            field=models.CharField(choices=[('DAILY', 'Daily Reading'), ('WEEKLY', 'Weekly Study'), ('TOPICAL', 'Topical Study')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='biblereadingplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='biblereadingplan',
            name='total_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biblereadingplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='biblereadingplan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='CounselingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('reason', models.CharField(choices=[('PREMARITAL', 'Premarital Counseling'), ('MARRIAGE', 'Marriage Counseling'), ('CONFLICT', 'Conflict Resolution'), ('SPIRITUAL', 'Spiritual Growth'), ('OTHER', 'Other')], max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_sessions', to=settings.AUTH_USER_MODEL)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.coupleprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
