# Generated by Django 5.1.6 on 2025-02-18 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_newbelieverprofile_approval_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marriagecounseling',
            name='couple',
        ),
        migrations.AlterUniqueTogether(
            name='marriageenrollment',
            unique_together={('program',)},
        ),
        migrations.AddField(
            model_name='coupleprofile',
            name='last_reading_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupleprofile',
            name='reading_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupleprofile',
            name='anniversary',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupleprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupleprofile',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='coupleprofile',
            name='partner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupleprofile',
            name='partner_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.RemoveField(
            model_name='marriageenrollment',
            name='couple',
        ),
    ]
