# Generated by Django 5.1.6 on 2025-02-19 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_womensministry_ministryevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('ministry_type', models.CharField(choices=[('BIBLE_STUDY', 'Bible Study'), ('DISCIPLESHIP', 'Discipleship'), ('MENTORSHIP', 'Mentorship'), ('OUTREACH', 'Outreach'), ('LEADERSHIP', 'Leadership'), ('FELLOWSHIP', 'Fellowship')], max_length=50)),
                ('meeting_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mens_ministry/')),
                ('is_active', models.BooleanField(default=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_mens_ministries', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='mens_ministry_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Men's Ministries",
            },
        ),
        migrations.CreateModel(
            name='MensEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mens_events/')),
                ('event_type', models.CharField(choices=[('BIBLE_STUDY', 'Bible Study'), ('DISCIPLESHIP', 'Discipleship'), ('MENTORSHIP', 'Mentorship'), ('OUTREACH', 'Outreach'), ('LEADERSHIP', 'Leadership'), ('FELLOWSHIP', 'Fellowship')], max_length=50)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='mens_ministry_events', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='services.mensministry')),
            ],
        ),
    ]
