# Generated by Django 5.1.6 on 2025-02-19 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_mensministry_mensevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youthevent',
            options={},
        ),
        migrations.RenameField(
            model_name='youthevent',
            old_name='is_featured',
            new_name='permission_slip_required',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='leaders',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='parent_consent_required',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='registration_fee',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='time',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='transportation_provided',
        ),
        migrations.RemoveField(
            model_name='youthevent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='youthevent',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='youthevent',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youthevent',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='youthevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='youth_events/'),
        ),
        migrations.AlterField(
            model_name='youthevent',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='YouthEventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('permission_slip_submitted', models.BooleanField(default=False)),
                ('payment_completed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.youthevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PermissionSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='permission_slips/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permission_slips', to=settings.AUTH_USER_MODEL)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.youtheventattendee')),
            ],
        ),
        migrations.AddField(
            model_name='youthevent',
            name='attendees',
            field=models.ManyToManyField(related_name='youth_events_attending', through='services.YouthEventAttendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='YouthEventPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.youtheventattendee')),
            ],
        ),
        migrations.CreateModel(
            name='YouthProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('WORSHIP', 'Worship Team'), ('BIBLE_STUDY', 'Bible Study'), ('MENTORSHIP', 'Mentorship'), ('OUTREACH', 'Outreach'), ('SPORTS', 'Sports Ministry'), ('ARTS', 'Arts & Music'), ('LEADERSHIP', 'Leadership Development')], max_length=50)),
                ('age_group', models.CharField(choices=[('13-15', 'Young Teens (13-15)'), ('16-18', 'Older Teens (16-18)'), ('19-25', 'Young Adults (19-25)')], max_length=20)),
                ('meeting_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='youth_programs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True)),
                ('parent_consent_required', models.BooleanField(default=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_youth_programs', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='youth_program_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='youthevent',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='services.youthprogram'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.youthevent')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.youtheventattendee')),
            ],
            options={
                'unique_together': {('event', 'attendee')},
            },
        ),
    ]
