# Generated by Django 5.1.6 on 2025-02-20 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_youthevent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='child',
            name='emergency_phone',
        ),
        migrations.AddField(
            model_name='child',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='child',
            name='pickup_allowed_by',
            field=models.TextField(help_text='Names of people allowed to pick up the child', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='special_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='emergency_contact',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ChildAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('pickup_person', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_performed', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.child')),
            ],
        ),
        migrations.CreateModel(
            name='ChildEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('attendance_record', models.ManyToManyField(blank=True, related_name='enrollments', to='services.childattendance')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.child')),
            ],
        ),
        migrations.CreateModel(
            name='ChildrensMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('age_group', models.CharField(choices=[('2-4', 'Toddlers (2-4)'), ('5-7', 'Early Elementary (5-7)'), ('8-10', 'Elementary (8-10)'), ('11-12', 'Pre-Teens (11-12)')], max_length=20)),
                ('program_type', models.CharField(choices=[('SUNDAY_SCHOOL', 'Sunday School'), ('BIBLE_CLUB', 'Bible Club'), ('VACATION_BIBLE', 'Vacation Bible School'), ('CHOIR', "Children's Choir"), ('ARTS_CRAFTS', 'Arts & Crafts'), ('DRAMA', 'Drama Ministry'), ('MISSIONS', 'Kids Missions')], max_length=50)),
                ('meeting_time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='childrens_ministry/')),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculum/')),
                ('safety_guidelines', models.TextField(blank=True)),
                ('allergies_aware', models.BooleanField(default=True)),
                ('children', models.ManyToManyField(related_name='enrolled_programs', through='services.ChildEnrollment', to='services.child')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_childrens_ministries', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_ministries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='childenrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.childrensministry'),
        ),
        migrations.AddField(
            model_name='childattendance',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.childrensministry'),
        ),
        migrations.DeleteModel(
            name='ChildrenMinistry',
        ),
    ]
