# Generated by Django 5.1.6 on 2025-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_healthresource_seniorsministry_seniorsevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seniorsevent",
            name="ministry",
            field=models.CharField(
                choices=[
                    ("BIBLE_STUDY", "Bible Study"),
                    ("FELLOWSHIP", "Fellowship Gathering"),
                    ("PRAYER", "Prayer Meeting"),
                    ("OUTREACH", "Community Outreach"),
                    ("VISITATION", "Home Visitation"),
                    ("WORKSHOP", "Life Skills Workshop"),
                    ("HEALTH", "Health & Wellness"),
                ],
                default="BIBLE_STUDY",
                max_length=100,
            ),
        ),
    ]
