# Generated by Django 5.1.6 on 2025-02-20 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0016_alter_seniorsevent_ministry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SinglesResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RELATIONSHIP", "Relationship Advice"),
                            ("SPIRITUAL", "Spiritual Growth"),
                            ("CAREER", "Career Development"),
                            ("PERSONAL", "Personal Development"),
                            ("DATING", "Dating Guidelines"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="singles_resources/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MentorshipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("areas_of_focus", models.TextField()),
                ("preferred_meeting_times", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MATCHED", "Matched"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SinglesMinistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("BIBLE_STUDY", "Bible Study"),
                            ("FELLOWSHIP", "Fellowship Group"),
                            ("PRAYER", "Prayer Meeting"),
                            ("SOCIAL", "Social Event"),
                            ("WORKSHOP", "Life Skills Workshop"),
                            ("MENTORSHIP", "Mentorship Program"),
                            ("OUTREACH", "Community Outreach"),
                        ],
                        max_length=50,
                    ),
                ),
                ("meeting_time", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="singles_ministry/"
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("18-25", "18-25 years"),
                            ("26-35", "26-35 years"),
                            ("36-45", "36-45 years"),
                            ("46+", "46+ years"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "relationship_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("guidelines", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "leader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_singles_ministries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="singles_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Singles Ministries",
            },
        ),
        migrations.CreateModel(
            name="SinglesEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="singles_events/"
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("registration_deadline", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_couples_allowed", models.BooleanField(default=False)),
                (
                    "event_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("dress_code", models.CharField(blank=True, max_length=200)),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        related_name="singles_events_attending",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="services.singlesministry",
                    ),
                ),
            ],
        ),
    ]
