# Generated by Django 5.1.6 on 2025-02-21 13:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0017_singlesresource_mentorshiprequest_singlesministry_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sermonnote",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameField(
            model_name="sermonnote",
            old_name="user",
            new_name="created_by",
        ),
        migrations.RemoveField(
            model_name="sermonnote",
            name="content",
        ),
        migrations.RemoveField(
            model_name="sermonnote",
            name="sermon",
        ),
        migrations.RemoveField(
            model_name="sermonnote",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="additional_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="audio_recording",
            field=models.FileField(blank=True, upload_to="sermon_audio/"),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="category",
            field=models.CharField(
                choices=[
                    ("SU", "Sunday Service"),
                    ("MI", "Midweek Service"),
                    ("RE", "Revival"),
                    ("CO", "Conference"),
                    ("YO", "Youth Service"),
                    ("OT", "Other"),
                ],
                default="SU",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="conclusion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="introduction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="key_verses",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="main_points",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="practical_applications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="preacher",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="presentation_file",
            field=models.FileField(blank=True, upload_to="sermon_presentations/"),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="scripture_reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="tags",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sermonnote",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name="sermonnote",
            index=models.Index(fields=["date"], name="services_se_date_c0c9bc_idx"),
        ),
        migrations.AddIndex(
            model_name="sermonnote",
            index=models.Index(
                fields=["category"], name="services_se_categor_03519a_idx"
            ),
        ),
    ]
