# Generated by Django 5.1.6 on 2025-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0018_alter_sermonnote_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="counselingrequest",
            options={},
        ),
        migrations.RemoveField(
            model_name="counselingrequest",
            name="additional_notes",
        ),
        migrations.RemoveField(
            model_name="counselingrequest",
            name="counselor",
        ),
        migrations.RemoveField(
            model_name="counselingrequest",
            name="couple",
        ),
        migrations.RemoveField(
            model_name="counselingrequest",
            name="preferred_date",
        ),
        migrations.RemoveField(
            model_name="counselingrequest",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="counselingrequest",
            name="scheduled_date",
        ),
        migrations.RemoveField(
            model_name="counselingrequest",
            name="status",
        ),
        migrations.RemoveField(
            model_name="counselingrequest",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="counseling_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("marriage", "Marriage Counseling"),
                    ("premarital", "Premarital Counseling"),
                    ("couples", "Couples Therapy"),
                    ("family", "Family Counseling"),
                    ("children", "Children & Adolescent Counseling"),
                    ("individual", "Individual Counseling"),
                    ("grief", "Grief & Loss Counseling"),
                    ("addiction", "Addiction Recovery"),
                    ("mental_health", "Mental Health Counseling"),
                    ("career", "Career Counseling"),
                    ("spiritual", "Spiritual Counseling"),
                    ("trauma", "Trauma & PTSD"),
                    ("other", "Other"),
                ],
                default="individual",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="other_category",
            field=models.CharField(
                blank=True,
                help_text="Please specify if you selected 'Other' as category",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="preferred_contact",
            field=models.CharField(
                choices=[("email", "Email"), ("phone", "Phone")],
                default="email",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="preferred_days",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="previous_counseling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="reason_for_counseling",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="counselingrequest",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("urgent", "Urgent"),
                    ("emergency", "Emergency"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="counselingrequest",
            name="preferred_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morning", "Morning (9AM - 12PM)"),
                    ("afternoon", "Afternoon (12PM - 5PM)"),
                    ("evening", "Evening (5PM - 8PM)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
