# Generated by Django 5.1.6 on 2025-03-14 06:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0019_alter_counselingrequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupleprofile",
            name="last_reading_date",
        ),
        migrations.RemoveField(
            model_name="coupleprofile",
            name="reading_streak",
        ),
        migrations.AlterField(
            model_name="coupleprofile",
            name="anniversary",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="coupleprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_couple_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="coupleprofile",
            name="partner_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="coupleprofile",
            name="partner_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="coupleprofile",
            name="partner_phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
