# Generated by Django 5.1.6 on 2025-03-17 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0020_remove_coupleprofile_last_reading_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("video", "Video"),
                            ("link", "External Link"),
                            ("activity", "Activity Sheet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="children_resources/"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("2-4", "Toddlers (2-4 years)"),
                            ("5-7", "Early Elementary (5-7 years)"),
                            ("8-11", "Upper Elementary (8-11 years)"),
                            ("all", "All Ages"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="childenrollment",
            name="attendance_record",
        ),
        migrations.RemoveField(
            model_name="childenrollment",
            name="child",
        ),
        migrations.RemoveField(
            model_name="childenrollment",
            name="program",
        ),
        migrations.RemoveField(
            model_name="child",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="child",
            name="medical_notes",
        ),
        migrations.RemoveField(
            model_name="child",
            name="pickup_allowed_by",
        ),
        migrations.AddField(
            model_name="child",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="child",
            name="emergency_contact_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="emergency_contact_phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="child",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="first_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="last_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="special_needs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ChildProgramEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_date", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="services.child"
                    ),
                ),
                (
                    "children_ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.childrensministry",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="services.childrenprogram",
                    ),
                ),
            ],
            options={
                "unique_together": {("child", "program")},
            },
        ),
        migrations.AlterField(
            model_name="childrensministry",
            name="children",
            field=models.ManyToManyField(
                related_name="enrolled_programs",
                through="services.ChildProgramEnrollment",
                to="services.child",
            ),
        ),
        migrations.DeleteModel(
            name="ChildAttendance",
        ),
        migrations.DeleteModel(
            name="ChildEnrollment",
        ),
    ]
