# Generated by Django 5.1.6 on 2025-03-17 15:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0021_childresource_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "check_in_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "checkout_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("absent", "Absent"),
                            ("early", "Early Departure"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("security_code", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("health_check_passed", models.BooleanField(default=True)),
                ("health_notes", models.TextField(blank=True)),
                (
                    "authorized_pickup_person",
                    models.CharField(blank=True, max_length=100),
                ),
                ("pickup_verification", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="services.child",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="services.childrenprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Child Attendance",
                "verbose_name_plural": "Child Attendance Records",
                "ordering": ["-date", "-check_in_time"],
                "unique_together": {("child", "program", "date")},
            },
        ),
    ]
