# Generated by Django 5.1.6 on 2025-03-18 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0022_childattendance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="childrenprogram",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="children_programs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
