# Generated by Django 5.1.6 on 2025-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0023_alter_childrenprogram_teachers"),
    ]

    operations = [
        migrations.AddField(
            model_name="childrenprogram",
            name="registrations",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
