# Generated by Django 5.1.6 on 2025-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0024_childrenprogram_registrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childrenprogram",
            name="registrations",
            field=models.IntegerField(default=0),
        ),
    ]
