# Generated by Django 5.1.6 on 2025-03-18 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0025_alter_childrenprogram_registrations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childrenprogram",
            name="registrations",
        ),
        migrations.AddField(
            model_name="childrenprogram",
            name="registrations",
            field=models.ManyToManyField(
                blank=True, related_name="registrations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
