# Generated by Django 5.1.6 on 2025-03-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0027_biblestudyregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="childrenprogram",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
