# Generated by Django 5.1.6 on 2025-03-19 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0028_childrenprogram_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="prayerrequest",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prayer_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
