# Generated by Django 5.1.6 on 2025-03-21 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0029_alter_prayerrequest_requester"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="child",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="child",
            name="emergency_contact_phone",
        ),
        migrations.RemoveField(
            model_name="child",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="child",
            name="photo_permission",
        ),
        migrations.RemoveField(
            model_name="child",
            name="special_needs",
        ),
        migrations.AddField(
            model_name="child",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="child",
            name="user_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="childprogramenrollment",
            name="attended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="childprogramenrollment",
            name="check_in_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="childprogramenrollment",
            name="check_out_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="child",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
