# Generated by Django 5.1.6 on 2025-03-24 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0031_alter_coupleprofile_partner_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupleprofile",
            name="user",
        ),
        migrations.AlterField(
            model_name="coupleprofile",
            name="partner_name",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="couple_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
