# Generated by Django 5.1.6 on 2025-03-24 12:28

import django.utils.timezone
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0033_coupleprofile_user_alter_coupleprofile_partner_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marriageministry",
            name="description",
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marriageministry",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="marriageministry",
            name="meeting_time",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="marriageministry",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
