# Generated by Django 5.1.6 on 2025-03-24 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0034_alter_marriageministry_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupleprofile",
            name="last_reading_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
