# Generated by Django 5.1.6 on 2025-03-25 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0035_coupleprofile_last_reading_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="marriageministry",
            name="image",
            field=models.ImageField(default="static/img/coc.png", upload_to=""),
        ),
        migrations.CreateModel(
            name="MarriageRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spouse_name", models.CharField(max_length=100)),
                (
                    "spouse_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("years_married", models.PositiveIntegerField(blank=True, null=True)),
                ("special_requests", models.TextField(blank=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.marriageministry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "ministry")},
            },
        ),
    ]
