# Generated by Django 5.1.6 on 2025-03-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0036_marriageministry_image_marriageregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="marriageministry",
            name="requirements",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
