# Generated by Django 5.1.6 on 2025-02-28 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadershipAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("self", "Self Assessment"),
                            ("peer", "Peer Review"),
                            ("mentor", "Mentor Evaluation"),
                            ("practical", "Practical Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("criteria", models.TextField()),
                ("passing_score", models.PositiveIntegerField()),
                (
                    "due_days",
                    models.PositiveIntegerField(
                        help_text="Days to complete after session"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_text", models.TextField()),
                (
                    "evidence_file",
                    models.FileField(blank=True, upload_to="leadership/submissions/"),
                ),
                ("submitted_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("revision", "Needs Revision"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("reviewed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.leadershipassessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadershipTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pastoral", "Pastoral Leadership"),
                            ("ministry", "Ministry Leadership"),
                            ("youth", "Youth Leadership"),
                            ("worship", "Worship Leadership"),
                            ("admin", "Administrative Leadership"),
                            ("missions", "Missions Leadership"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Leadership"),
                            ("intermediate", "Intermediate Leadership"),
                            ("advanced", "Advanced Leadership"),
                            ("mentor", "Mentorship Training"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("learning_objectives", models.TextField()),
                ("prerequisites", models.TextField(blank=True)),
                ("duration_weeks", models.PositiveIntegerField()),
                ("max_participants", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="leadership/courses/"),
                ),
                (
                    "syllabus",
                    models.FileField(blank=True, upload_to="leadership/syllabi/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentored_trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentorshipSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("topics", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("completed", models.BooleanField(default=False)),
                ("feedback", models.TextField(blank=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentoring_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.leadershiptraining",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField()),
                ("competencies", models.TextField()),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="education.leadershiptraining",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("training", "order")},
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("practical_exercise", models.TextField()),
                ("reflection_questions", models.TextField()),
                ("resources", models.TextField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("order", models.PositiveIntegerField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="education.trainingmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("module", "order")},
            },
        ),
        migrations.AddField(
            model_name="leadershipassessment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="education.trainingsession",
            ),
        ),
        migrations.CreateModel(
            name="ParticipantEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                            ("on_hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("enrolled_date", models.DateTimeField(auto_now_add=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.leadershiptraining",
                    ),
                ),
            ],
            options={
                "unique_together": {("participant", "training")},
            },
        ),
    ]
