# Generated by Django 5.1.6 on 2025-03-04 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0002_leadershipassessment_assessmentsubmission_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age_range", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SundaySchoolMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bible_story", "Bible Story"),
                            ("memory_verse", "Memory Verse"),
                            ("activity", "Activity"),
                            ("craft", "Craft"),
                            ("song", "Song"),
                            ("lesson", "Full Lesson"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("bible_reference", models.CharField(max_length=100)),
                ("main_points", models.TextField()),
                ("learning_objectives", models.TextField()),
                ("materials_needed", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("teacher_notes", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(blank=True, upload_to="sunday_school/materials/"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="sunday_school/images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "age_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.agegroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField()),
                ("used_date", models.DateField()),
                (
                    "age_group_effectiveness",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "time_management",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "student_engagement",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("suggestions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.sundayschoolmaterial",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("instructions", models.TextField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("materials_needed", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="sunday_school/activities/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.sundayschoolmaterial",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TeachingResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("worksheet", "Worksheet"),
                            ("handout", "Handout"),
                            ("presentation", "Presentation"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("game", "Game"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="sunday_school/resources/")),
                ("is_downloadable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.sundayschoolmaterial",
                    ),
                ),
            ],
        ),
    ]
