# Generated by Django 5.1.6 on 2025-03-04 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "education",
            "0004_theologicalcategory_theologicalresource_studynote_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChristianDiscussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Christian Discussion",
                "verbose_name_plural": "Christian Discussions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChristianEducationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Christian Education Level",
                "verbose_name_plural": "Christian Education Levels",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChristianDiscussionPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="christian_discussion_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="education.christiandiscussion",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="education.christiandiscussionpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Christian Discussion Post",
                "verbose_name_plural": "Christian Discussion Posts",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChristianCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bible_study", "Bible Study"),
                            ("theology", "Theology"),
                            ("apologetics", "Apologetics"),
                            ("ministry", "Ministry"),
                            ("discipleship", "Discipleship"),
                            ("leadership", "Leadership"),
                            ("missions", "Missions"),
                            ("ethics", "Christian Ethics"),
                        ],
                        max_length=20,
                    ),
                ),
                ("objectives", models.TextField()),
                ("prerequisites", models.TextField(blank=True)),
                ("duration_weeks", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="christian_education/courses/"
                    ),
                ),
                (
                    "syllabus",
                    models.FileField(
                        blank=True, upload_to="christian_education/syllabi/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="christian_courses_teaching",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="education.christianeducationlevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Christian Course",
                "verbose_name_plural": "Christian Courses",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ChristianModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("scripture_references", models.TextField()),
                ("learning_activities", models.TextField()),
                ("resources", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="education.christiancourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Christian Module",
                "verbose_name_plural": "Christian Modules",
                "ordering": ["course", "order", "title"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.AddField(
            model_name="christiandiscussion",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussions",
                to="education.christianmodule",
            ),
        ),
        migrations.CreateModel(
            name="ChristianAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("essay", "Essay"),
                            ("project", "Project"),
                            ("presentation", "Presentation"),
                            ("discussion", "Discussion"),
                        ],
                        max_length=20,
                        verbose_name="Assignment Type",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Due Date")),
                ("points", models.PositiveIntegerField(verbose_name="Points")),
                ("instructions", models.TextField(verbose_name="Instructions")),
                ("rubric", models.TextField(blank=True, verbose_name="Rubric")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="education.christianmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Christian Assignment",
                "verbose_name_plural": "Christian Assignments",
                "ordering": ["module", "due_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="ChristianAssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="christian_education/submissions/"
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("graded_date", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="education.christianassignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="christian_graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="christian_assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Christian Assignment Submission",
                "verbose_name_plural": "Christian Assignment Submissions",
                "ordering": ["-submission_date"],
                "unique_together": {("assignment", "student")},
            },
        ),
        migrations.CreateModel(
            name="ChristianEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("enrolled_date", models.DateTimeField(auto_now_add=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("progress", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="education.christiancourse",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="christian_course_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Christian Enrollment",
                "verbose_name_plural": "Christian Enrollments",
                "ordering": ["-enrolled_date"],
                "unique_together": {("student", "course")},
            },
        ),
    ]
