# Generated by Django 5.1.6 on 2025-03-05 10:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0006_christianmentorprofile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BibleCollegeProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("bachelors", "Bachelor's Degree"),
                            ("masters", "Master's Degree"),
                            ("doctorate", "Doctorate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("duration_years", models.PositiveIntegerField()),
                ("credits_required", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bible College Program",
                "verbose_name_plural": "Bible College Programs",
            },
        ),
        migrations.CreateModel(
            name="BibleCollegeCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("credits", models.PositiveIntegerField()),
                (
                    "semester",
                    models.IntegerField(
                        choices=[(1, "First"), (2, "Second"), (3, "Summer")]
                    ),
                ),
                ("year_level", models.PositiveIntegerField()),
                (
                    "syllabus",
                    models.FileField(blank=True, upload_to="bible_college/syllabi/"),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True, to="education.biblecollegecourse"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_college_courses",
                        to="education.biblecollegeprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible College Course",
                "verbose_name_plural": "Bible College Courses",
            },
        ),
        migrations.CreateModel(
            name="BibleCollegeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("due_date", models.DateTimeField()),
                ("total_marks", models.PositiveIntegerField()),
                (
                    "weight_percentage",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_college_assignments",
                        to="education.biblecollegecourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible College Assignment",
                "verbose_name_plural": "Bible College Assignments",
            },
        ),
        migrations.CreateModel(
            name="BibleCollegeFaculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("qualifications", models.TextField()),
                ("bio", models.TextField()),
                ("office_hours", models.TextField()),
                (
                    "profile_image",
                    models.ImageField(blank=True, upload_to="bible_college/faculty/"),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="bible_college_instructors",
                        to="education.biblecollegecourse",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_college_faculty",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible College Faculty",
                "verbose_name_plural": "Bible College Faculty Members",
            },
        ),
        migrations.CreateModel(
            name="BibleCollegeStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("expected_graduation", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("leave", "On Leave"),
                            ("graduated", "Graduated"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_year", models.PositiveIntegerField()),
                (
                    "spiritual_reference",
                    models.FileField(blank=True, upload_to="bible_college/references/"),
                ),
                ("testimony", models.TextField()),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_college_students",
                        to="education.biblecollegeprogram",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_college_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible College Student",
                "verbose_name_plural": "Bible College Students",
            },
        ),
        migrations.CreateModel(
            name="BibleCollegeEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        choices=[(1, "First"), (2, "Second"), (3, "Summer")]
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                            ("P", "Pass"),
                            ("I", "Incomplete"),
                            ("W", "Withdrawn"),
                        ],
                        max_length=2,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_college_enrollments",
                        to="education.biblecollegecourse",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_college_enrollments",
                        to="education.biblecollegestudent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible College Enrollment",
                "verbose_name_plural": "Bible College Enrollments",
                "unique_together": {("student", "course", "semester", "year")},
            },
        ),
        migrations.CreateModel(
            name="BibleCollegeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_file",
                    models.FileField(upload_to="bible_college/assignments/"),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("marks_obtained", models.PositiveIntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_college_submissions",
                        to="education.biblecollegeassignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bible_college_submissions",
                        to="education.biblecollegestudent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible College Submission",
                "verbose_name_plural": "Bible College Submissions",
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
