# Generated by Django 5.1.6 on 2025-03-05 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0007_biblecollegeprogram_biblecollegecourse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biblecollegeprogram",
            name="level",
            field=models.CharField(
                choices=[
                    ("certificate", "Certificate"),
                    ("diploma", "Diploma"),
                    ("bachelors", "Bachelor's Degree"),
                    ("masters", "Master's Degree"),
                    ("doctorate", "Doctorate"),
                ],
                default="certificate",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="biblecollegestudent",
            name="expected_graduation",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
