# Generated by Django 5.1.6 on 2025-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0008_alter_biblecollegeprogram_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biblecollegestudent",
            name="current_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
