# Generated by Django 5.1.6 on 2025-02-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0002_mission_project_projectupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvangelismTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tract", "Gospel Tract"),
                            ("book", "Book"),
                            ("video", "Video Resource"),
                            ("audio", "Audio Resource"),
                            ("presentation", "Presentation"),
                            ("training", "Training Material"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("pt", "Portuguese"),
                            ("other", "Other"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="evangelism_tools/"
                    ),
                ),
                ("external_link", models.URLField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="evangelism_tools/thumbnails/"
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=100)),
                ("publisher", models.CharField(blank=True, max_length=100)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
