# Generated by Django 5.1.6 on 2025-02-27 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0007_inmateprogram_prisonfacility_ministryresource_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("contact_person", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
                ("visiting_hours", models.TextField()),
                (
                    "special_instructions",
                    models.TextField(help_text="Special requirements or protocols"),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("floor", models.CharField(max_length=50)),
                ("visiting_restrictions", models.TextField(blank=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outreach.hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinistryService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("prayer", "Prayer Support"),
                            ("communion", "Holy Communion"),
                            ("counseling", "Spiritual Counseling"),
                            ("worship", "Worship Service"),
                            ("visitation", "General Visitation"),
                            ("support_group", "Support Group"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                ("max_participants", models.PositiveIntegerField()),
                ("materials_needed", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("departments", models.ManyToManyField(to="outreach.department")),
            ],
        ),
        migrations.CreateModel(
            name="HospitalVolunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("availability", models.TextField()),
                ("emergency_contact", models.CharField(max_length=100)),
                ("emergency_phone", models.CharField(max_length=20)),
                ("medical_training", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("orientation_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hospitals", models.ManyToManyField(to="outreach.hospital")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("services", models.ManyToManyField(to="outreach.ministryservice")),
            ],
        ),
        migrations.CreateModel(
            name="PatientRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("room_number", models.CharField(max_length=20)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("normal", "Normal"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("special_notes", models.TextField(blank=True)),
                ("preferred_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outreach.department",
                    ),
                ),
                (
                    "service_requested",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outreach.ministryservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrisonVisitReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("inmates_attended", models.PositiveIntegerField()),
                ("activities_conducted", models.TextField()),
                ("prayer_requests", models.TextField(blank=True)),
                ("testimonies", models.TextField(blank=True)),
                ("challenges", models.TextField(blank=True)),
                ("follow_up_needed", models.TextField(blank=True)),
                ("resources_used", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outreach.prisonvisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prison Visit Report",
                "verbose_name_plural": "Prison Visit Reports",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="VisitSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outreach.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outreach.hospital",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outreach.ministryservice",
                    ),
                ),
                (
                    "volunteers",
                    models.ManyToManyField(
                        related_name="hospital_visits", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalVisitReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("patients_visited", models.PositiveIntegerField()),
                ("prayer_requests", models.TextField(blank=True)),
                ("testimonies", models.TextField(blank=True)),
                ("challenges", models.TextField(blank=True)),
                ("follow_up_needed", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outreach.visitschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospital Visit Report",
                "verbose_name_plural": "Hospital Visit Reports",
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="VisitReport",
        ),
    ]
