# Generated by Django 5.1.6 on 2025-03-10 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0008_hospital_department_ministryservice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="church_donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
