# Generated by Django 5.1.6 on 2025-03-06 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="livestream",
            old_name="streamer",
            new_name="created_by",
        ),
        migrations.RemoveField(
            model_name="livestream",
            name="actual_start_time",
        ),
        migrations.AlterField(
            model_name="livestream",
            name="scheduled_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="thumbnail",
            field=models.ImageField(
                blank=True, default="coc.png", upload_to="livestreams/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="livestream",
            name="viewers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="StreamChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="events.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
