# Generated by Django 5.1.6 on 2025-03-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="can_register",
            field=models.BooleanField(default=True),
        ),
    ]
