# Generated by Django 5.1.2 on 2025-02-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0011_videonotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('video', 'Video Notification'), ('email', 'Email Notification'),
                                            ('account', 'Account Notification'), ('other', 'Other Notification')],
                                   default='account', max_length=155),
        ),
    ]
